Not publishing gimbal data
heimdallpower/Onboard-SDK-ROS pull request #14
Opened 2022-12-08 12:04 UTC by mBerdal

2022-12-08 12:46 UTC, MadsBornebusch approved these changes, later dismissed

2022-12-12 11:59 UTC, mikkelti requested changes

2022-12-12 11:59 UTC, mikkelti commented on dji_sdk/src/modules/dji_sdk_node.cpp
>    // TODO: documentation and proper frame id
Can you remove this line as well? If it was related to the gimbal stuff.

2022-12-13 09:41 UTC, mikkelti approved these changes

2022-12-13 09:41 UTC, merged