DRONE-284 Add topic 'dji_sdk/imu_raw'
heimdallpower/Onboard-SDK-ROS pull request #6
Opened 2022-03-30 15:29 UTC by mBerdal

2022-03-30 15:34 UTC, MadsBornebusch requested changes

2022-03-30 15:34 UTC, MadsBornebusch commented on dji_sdk/src/modules/dji_sdk_node_publisher.cpp
> +  imu_raw_FLU.header.stamp = ros::Time::now();
Use msg_time as the other messages

2022-03-30 15:40 UTC, MadsBornebusch approved these changes

2025-02-11 07:57 UTC, mikkelti commented
Not necessary.

2025-02-11 07:57 UTC, closed without merging