Publish compass health with stamp
heimdallpower/Onboard-SDK-ROS pull request #9
Opened 2022-06-22 11:10 UTC by mBerdal

2022-07-08 06:27 UTC, mBerdal commented
@mikkelti Please have a look

2022-08-01 11:25 UTC, mikkelti requested changes

2022-08-01 11:25 UTC, mikkelti commented on dji_sdk/src/modules/dji_sdk_node_publisher.cpp
> +  gps_health.header.frame_id  = "/gps";
I don't think this message needs a frame id
```suggestion
```

2022-08-02 09:15 UTC, mikkelti approved these changes

2022-08-02 09:15 UTC, merged